language: cpp
dist: bionic
compiler: gcc
services:
    - docker
script:
    - ./configure-static
    - ./build-static
deploy:
    provider: releases
    api_key: $PWA_TO_TWA_ACCESS_KEY
    skip_cleanup: true
    file:
        - pwa-to-twa
    on:
        tags: true
branches:
    only:
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

