#!/bin/sh

docker run --rm -it -v $(pwd):/app fffaraz/qt:static /bin/bash -c "cd /app/libgit && git submodule init && git submodule update && mkdir -p build && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF .. && cmake --build . && cd /app && qmake pwa-to-twa.pro && make"
